// Automatically generated by scripts/generate-manifest.ts
// Do not edit this file manually.

// Pre-compiled Regexes for maximum performance on Cloudflare Workers
export const ROUTE_REGEXPS: Array<RegExp> = [
  /^\/admin\/?$/,
  /^\/atom\.xml\/?$/,
  /^\/feed\.json\/?$/,
  /^\/robots\.txt\/?$/,
  /^\/rss\.xml\/?$/,
  /^\/site\.webmanifest\/?$/,
  /^\/sitemap\.xml\/?$/,
  /^\/admin\/posts\/?$/,
  /^\/forgot-password\/?$/,
  /^\/login\/?$/,
  /^\/register\/?$/,
  /^\/reset-link\/?$/,
  /^\/verify-email\/?$/,
  /^\/friend-links\/?$/,
  /^\/posts\/?$/,
  /^\/search\/?$/,
  /^\/unsubscribe\/?$/,
  /^\/profile\/?$/,
  /^\/submit-friend-link\/?$/,
  /^\/$/,
  /^\/post\/[^/]+\/?$/,
  /^\/admin\/comments\/?$/,
  /^\/admin\/friend-links\/?$/,
  /^\/admin\/media\/?$/,
  /^\/admin\/settings\/?$/,
  /^\/admin\/tags\/?$/,
  /^\/admin\/posts\/edit\/[^/]+\/?$/,
];

/**
 * Checks if the path matches any valid route.
 * O(n) regex checks, but zero compilation overhead at runtime.
 */
export function isPathValid(path: string): boolean {
  return ROUTE_REGEXPS.some((regex) => regex.test(path));
}
